name: Save Gas Reading

on:
  issues:
    types: [opened]

jobs:
  save:

    if: contains(github.event.issue.title,'gas-reading')

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:

      - uses: actions/checkout@v3

      - name: Save reading
        run: |
          echo "$(date +%F),${{ github.event.issue.body }}" >> gas_readings.txt

      - name: Commit change
        env:
          TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://x-access-token:$TOKEN@github.com/${{ github.repository }}
          git add gas_readings.txt
          git commit -m "Add gas reading" || echo "No change"
          git push